byog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from common.views import HomePageView, TOSView
from parts import urls as parts_urls
from lists import list_urls, build_urls
from profiles import urls as profile_urls
from articles import urls as article_urls

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^tos/$', TOSView.as_view(), name='tos'),
    url(r'^operator/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^parts/', include(parts_urls)),
    url(r'^lists/', include(list_urls)),
    url(r'^builds/', include(build_urls)),
    url(r'^users/', include(profile_urls)),
    url(r'^article/', include(article_urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lists/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.dispatch import receiver
from django.utils.crypto import get_random_string

from byog.settings import AUTH_USER_MODEL
from common.models import RestrictedImageField, IMAGE_TYPES
from parts.part_info.categories import CATEGORY_CHOICES
from parts.part_info.vendors import VENDOR_CHOICES
from parts.part_info.currency import CURRENCY_CHOICES

import os
import uuid
import decimal

LIST_MAX_PRICE = decimal.Decimal(999999.99)


class ItemList(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.CharField(unique=True, max_length=7)
    active = models.BooleanField(default=True)
    complete = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    title = models.CharField(default='', max_length=100)
    deck = models.CharField(default='', max_length=140)
    description = models.TextField(default='', max_length=5000)
    total_price = models.DecimalField(max_digits=8, decimal_places=2, default=0, blank=True)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='USD')
    date = models.DateTimeField(null=True)

    def save(self, *args, **kwargs):
        """
        Randomly generates a slug on creation
        """
        if not self.slug:
            self.slug = get_random_string(length=7)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        if not self.complete:
            return reverse('list_public', kwargs={'slug': self.slug})
        if self.complete:
            return reverse('build_manage', kwargs={'slug': self.slug})

    def __str__(self):
        return "{} - {}".format(self.user, self.title)


class Build(ItemList):

    class Meta:
        proxy = True


class BuildVote(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    build = models.ForeignKey('ItemList', on_delete=models.CASCADE)

    class Meta:
        unique_together = (
            ('user', 'build')
        )


class Item(models.Model):
    itemlist = models.ForeignKey('ItemList', on_delete=models.CASCADE)
    part = models.ForeignKey('parts.Part', on_delete=models.CASCADE)
    # Since sorted() treats foreignkey values as strings rather than objects, it needs to be set again for the Item
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES, default='', blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    custom_price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    vendor = models.CharField(max_length=15, choices=VENDOR_CHOICES, null=True, blank=True)

    def __str__(self):
        return str(self.part)

    def save(self, *args, **kwargs):
        """
        If the user hasn't selected a vendor, set the vendor with the lowest price
        Automatically set the item category based on the part category
        """
        if not self.vendor:
            self.vendor = self.part.lowest_price_vendor
            self.price = self.part.lowest_price
        if not self.category:
            self.category = self.part.category

        super().save(*args, **kwargs)


class CustomItem(models.Model):
    itemlist = models.ForeignKey('ItemList', on_delete=models.CASCADE)
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES)
    part = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    url = models.URLField(default='', blank=True)

    def __str__(self):
        return "{} - {}".format(self.get_category_display(), self.part)

    @property
    def name(self):
        return self.__str__()


# From http://stackoverflow.com/questions/2673647/enforce-unique-upload-file-names-using-django
def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('img/builds/', filename)


class BuildImage(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    build = models.ForeignKey('ItemList', on_delete=models.CASCADE)
    image = RestrictedImageField(upload_to=get_file_path, content_types=IMAGE_TYPES,
                                 max_upload_size=5242880, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.user:
            self.user = self.build.user
        super().save(*args, **kwargs)


# From http://stackoverflow.com/a/16041527
@receiver(models.signals.post_delete, sender=BuildImage)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes an uploaded image on disk when the associated model is deleted"""

    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=BuildImage)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes file from filesystem when corresponding buildimage object is changed."""

    if not instance.pk:
        return False

    try:
        old_image = BuildImage.objects.get(pk=instance.pk).image

    except BuildImage.DoesNotExist:
        return False

    new_image = instance.image
    if old_image:
        if not old_image == new_image:
            if os.path.isfile(old_image.path):
                os.remove(old_image.path)

parts/models.py
import os
import uuid
import decimal

from PIL import Image
from django.contrib.postgres.fields import JSONField
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Min, Avg
from django.dispatch import receiver
from django.utils.crypto import get_random_string
from django.utils.text import slugify
from sorl.thumbnail import ImageField

from byog.settings import AUTH_USER_MODEL
from parts.part_info.categories import CATEGORY_CHOICES
from parts.part_info.vendors import VENDOR_CHOICES
from parts.part_info.currency import CURRENCY_CHOICES


# From http://stackoverflow.com/questions/2673647/enforce-unique-upload-file-names-using-django
def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('img/parts/', filename)


class Part(models.Model):
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES, default='')
    manufacturer = models.CharField(max_length=100, default='')
    name = models.CharField(max_length=250, default='')
    product_num = models.CharField(max_length=50, null=True, unique=True, blank=True)
    specs = JSONField(default=dict(), blank=True)
    slug = models.CharField(unique=True, max_length=7)
    lowest_price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    image = ImageField(upload_to=get_file_path, null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_random_string(length=7)

        if not self.lowest_price:
            self.lowest_price = self.pricebase_set.all().aggregate(Min('price'))['price__min']

        if not self.image:
            try:
                self.image = self.partimage_set.first().image
            except AttributeError:
                pass

        if self.product_num == '':
            self.product_num = None

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('parts_detail', kwargs={'slug': self.slug, 'title': slugify(self.__str__())})

    @property
    def lowest_price_vendor(self):
        try:
            price = self.pricebase_set.all().order_by('price').first().vendor
            return price
        except AttributeError:
            return None

    def get_price(self, currency='USD'):
        currency_field = {'USD': self.lowest_price}
        currency_symbol = dict((currency, symbol) for currency, symbol in CURRENCY_CHOICES)

        if currency_field[currency]:
            return "{}{}".format(currency_symbol[currency], currency_field[currency])
        else:
            return None

    @property
    def avg_rating(self):
        reviews = self.partreview_set.filter(build__complete=True)
        if reviews:
            rating = float("{0:.2f}".format(reviews.aggregate(Avg('rating'))['rating__avg']))
        else:
            rating = 0.0

        total = reviews.count()
        average = (rating, total)
        return average


class PriceBase(models.Model):

    part = models.ForeignKey('Part', on_delete=models.CASCADE, default=None)
    vendor = models.CharField(max_length=15, choices=VENDOR_CHOICES)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='USD')
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    date = models.DateField(auto_now_add=True)
    url = models.URLField()

    def __str__(self):
        return self.vendor + ': {}'.format(self.get_currency_display()) + str(self.price)


@receiver(models.signals.post_save, sender=PriceBase)
def auto_update_part_lowest_price(sender, instance, **kwargs):
    """
    Updates a part's lowest_price field if the newly saved base price is lower than the part's current lowest price
    """

    if instance.price:
        if instance.part.lowest_price is None or decimal.Decimal(instance.price) < decimal.Decimal(instance.part.lowest_price):
            instance.part.lowest_price = instance.price
            instance.part.save()


class PricePromo(models.Model):
    base = models.ForeignKey('PriceBase', on_delete=models.CASCADE)
    discount = models.DecimalField(max_digits=6, decimal_places=2)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='USD')
    date_start = models.DateField(auto_now_add=True)
    date_end = models.DateField()
    expired = models.BooleanField(default=False)
    description = models.TextField(max_length=500, default='', blank=True)


class PartReview(models.Model):
    SCORE_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )

    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    part = models.ForeignKey('Part', on_delete=models.CASCADE)
    build = models.ForeignKey('lists.ItemList', on_delete=models.CASCADE)
    item = models.OneToOneField('lists.Item', on_delete=models.CASCADE)
    rating = models.SmallIntegerField(choices=SCORE_CHOICES)
    review = models.TextField(default='', max_length=5000)
    helpful = models.IntegerField(default=0)
    unhelpful = models.IntegerField(default=0)

    def __str__(self):
        return "{} - {}".format(self.part, self.user.username)

    def get_absolute_url(self):
        part = self.part
        return reverse('parts_review_detail', kwargs={'review_id': self.id, 'slug': part.slug, 'title': slugify(part.name)})

    class Meta:
        unique_together = (
            ('part', 'user')
        )

    @property
    def percent_helpful(self):

        if self.helpful + self.unhelpful > 0:

            return "{} of {} user(s) ({:.0%}) found this review helpful.".format(
                self.helpful, (self.helpful + self.unhelpful), (self.helpful / (self.helpful + self.unhelpful))
            )

        else:
            return None


class ReviewVote(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey('PartReview', on_delete=models.CASCADE)
    helpful = models.BooleanField()

    class Meta:
        unique_together = (
            ('review', 'user')
        )


class PartImage(models.Model):
    part = models.ForeignKey('Part', on_delete=models.CASCADE, default=None)
    image = ImageField(upload_to=get_file_path, blank=True)

    def save(self, *args, **kwargs):

        super().save(*args, **kwargs)

        # Resizes the image if it's larger than 500x400
        if self.image:
            filename = self.image
            thumb = Image.open(filename)
            if thumb.height > 400 or thumb.width > 500:
                thumb.thumbnail((500, 400))
                thumb.save(filename.path)


# From http://stackoverflow.com/a/16041527
@receiver(models.signals.post_delete, sender=PartImage)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes an uploaded image on disk when the associated model is deleted"""

    if instance.image:

        if instance.part.image == instance.image:
            instance.part.image = None
            instance.part.save()

        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=PartImage)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes file from filesystem when corresponding partimage object is changed."""

    if not instance.pk:
        return False

    try:
        old_image = PartImage.objects.get(pk=instance.pk).image

    except PartImage.DoesNotExist:
        return False

    new_image = instance.image

    if old_image:

        if not old_image == new_image:

            if instance.part.image == old_image:
                instance.part.image = new_image
                instance.part.save()

            if os.path.isfile(old_image.path):
                os.remove(old_image.path)


@receiver(models.signals.post_save, sender=PartImage)
def auto_add_part_image(sender, instance, **kwargs):
    """Adds an image to a part if one does not already exist"""

    if not instance.part.image:
        instance.part.image = instance.image
        instance.part.save()

templates/lists/build_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}Edit {{ title }} Details{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {% crispy form %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <p><a href="javascript:void(0);" class="pull-right toggle-guide">Formatting Guide</a></p>
            <br>
            <div class="formatting-guide" style="display: none;">
                <table class="table table-striped table-condensed table-bordered table-responsive markdown">
                    <thead>
                        <tr>
                            <th>Markdown</th>
                            <th>Result</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>*Italics*</td>
                            <td><i>Italics</i></td>
                        </tr>
                        <tr>
                            <td>**Bold**</td>
                            <td><b>Bold</b></td>
                        </tr>
                        <tr>
                            <td>~~Strikethrough~~</td>
                            <td><del>Strikethrough</del></td>
                        </tr>
                        <tr>
                            <td>Super^script^</td>
                            <td>Super<sup>script</sup></td>
                        </tr>
                        <tr>
                            <td>
                                # Header 1<br>
                                ## Header 2<br>
                                ### Header 3<br>
                            </td>
                            <td>
                                <h1 id="header-1">Header 1</h1>
                                <h2 id="header-2">Header 2</h2>
                                <h3 id="header-3">Header 3</h3>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Horizontal Rule<br>
                                ***
                            </td>
                            <td>
                                <p>Horizontal Rule</p>
                                <hr>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                * Unordered List Item 1<br>
                                * Unordered List Item 2<br>
                                * Unordered List Item 3
                            </td>
                            <td>
                                <ul>
                                    <li>Unordered List Item 1</li>
                                    <li>Unordered List Item 2</li>
                                    <li>Unordered List Item 2</li>
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                1. Ordered List Item 1<br>
                                2. Ordered List Item 2<br>
                                3. Ordered List Item 3
                            </td>
                            <td>
                                <ol>
                                    <li>Ordered List Item 1</li>
                                    <li>Ordered List Item 2</li>
                                    <li>Ordered List Item 3</li>
                                </ol>
                            </td>
                        </tr>
                        <tr>
                            <td>`Code`</td>
                            <td><code>Code</code></td>
                        </tr>
                        <tr>
                            <td>
                                <p>Normal Text<p>
                                <p style="white-space: pre;">    Preformatted Text</p>
                            </td>
                            <td>
                                <p>Normal Text<p>
                                <pre><code>Preformatted Text</code></pre>
                            </td>
                        </tr>
                        <tr>
                            <td>&lt;https://shiranai.moe&gt;</td>
                            <td><a href="https://shiranai.moe">https://shiranai.moe</a></td>
                        </tr>
                        <tr>
                            <td>[Fridey Night](https://shiranai.moe "Home Along")</td>
                            <td><a href="https://shiranai.moe" title="Home Along">Fridey Night</a></td>
                        </tr>
                        <tr>
                            <td>
                                &gt;Block Quote<br>
                                &gt;&gt;Nested Quote
                            </td>
                            <td>
                                <blockquote>
                                    Block Quote
                                    <blockquote>
                                        Nested Quote
                                    </blockquote>
                                </blockquote>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Left Aligned|Center Aligned|Right Aligned<br>
                                :---|:---:|---:<br>
                                Alpha|Bravo|Charlie<br>
                                Delta|Echo|Foxtrot<br>
                            </td>
                            <td>
                                <table class="table table-bordered table-responsive">
                                    <thead>
                                        <tr>
                                            <th>Left Aligned</th>
                                            <th>Center Aligned</th>
                                            <th>Right Aligned</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td align="left">Alpha</td>
                                            <td align="center">Bravo</td>
                                            <td align="right">Charlie</td>
                                        </tr>
                                        <tr>
                                            <td align="left">Delta</td>
                                            <td align="center">Echo</td>
                                            <td align="right">Foxtrot</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                [TOC]<br>
                                # TOC 1<br>
                                Table of Contents 1<br>
                                ## TOC 2<br>
                                Table of Contents 2<br>
                            </td>
                            <td>
                                <div class="toc">
                                    <ul>
                                        <li><a href="#toc-1">TOC 1</a>
                                            <ul>
                                                <li><a href="#toc-2">TOC 2</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                                <h1 id="toc-1">TOC 1</h1>
                                <p>Table of Contents 1</p>
                                <h2 id="toc-2">TOC 2</h2>
                                <p>Table of Contents 2</p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            $('.toggle-guide').click(function() {
                $('.formatting-guide').slideToggle();
            });
        });
    </script>
{% endblock %}

templates/lists/build_image.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block head_title %}{{ title }} Images | BYOG{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3 sidebar">
                {% crispy form %}
                <hr>
                <a href="{% url 'build_manage' slug %}" class="btn btn-default"><i class="fa fa-arrow-left fa-fw" aria-hidden="true"></i> Return To Build</a>
            </div>
            {% if images %}
                <div class="col-md-9" id="lightgallery">
                    {% for image in images %}
                        <div class="col-md-2 build-gallery">
                            <div>
                                <a href="{{ image.image.url }}" class="lightbox-img">
                                    {% thumbnail image.image "128x128" crop="center" as im %}
                                        <img src="{{ im.url }}" height="{{ im.height }}"
                                             width="{{ im.width }}"/>
                                    {% endthumbnail %}
                                </a>
                            </div>
                            <div>
                                <form method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-danger btn-xs" formaction="{% url 'build_image_del' image.id %}"><i class="fa fa-trash-o fa-fw" aria-hidden="true"></i> Delete Image</button>
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="col-md-9"><p>You haven't uploaded any images yet.</p></div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            $('#id_image').change(function () {
                $('#id_image_form').submit();
            });
            $("#lightgallery").lightGallery({
                selector: '.lightbox-img'
            });
        });
    </script>
    <script>

    </script>
{% endblock %}

templates/lists/build_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}

{% block head_title %}Completed Builds | BYOG{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                    {% for build in builds %}
                            <div class="row build-list">
                                <div class="col-md-3">
                                    <a href="{{ build.get_absolute_url }}">
                                        <div >
                                            {% if build.buildimage_set.all.0 %}
                                                {% thumbnail build.buildimage_set.all.0.image "260x150" crop="center" as im %}
                                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-responsive">
                                                {% endthumbnail %}
                                            {% else %}
                                                <img src="{% static 'img/No_image_available.png' %}" width="150" height="150" class="img-responsive">
                                            {% endif %}
                                        </div>
                                        <div>
                                            <span><b>{{ build.get_currency_display }}{{ build.total_price }}</b></span>
                                            <span class="pull-right"><i class="fa fa-thumbs-o-up fa-fw" aria-hidden="true"></i> {{ build.score }}</span>
                                        </div>
                                    </a>
                                </div>
                                <div class="col-md-9">
                                    <h3><a href="{{ build.get_absolute_url }}">{{ build.title }}</a></h3>
                                    <p>By <a href="{{ build.user.get_absolute_url }}">{{ build.user }}</a></p>
                                    <p>{{ build.deck }}</p>
                                </div>
                            </div>
                            {% if not forloop.last %}
                                <hr>
                            {% endif %}
                    {% endfor %}
            {% if is_paginated %}{% load paginator %}{% paginator 2 %}{% endif %}
            </div>
        </div>

    </div>

{% endblock %}

templates/lists/build_list_featured.html
{% extends 'lists/build_list.html' %}
{% load staticfiles %}
{% load thumbnail %}

{% block head_title %}Featured Builds | BYOG{% endblock %}

templates/lists/build_review_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_title %}{{ part }} Review | BYOG{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% crispy form %}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}

    <script>
        $(document).ready(function() {
            var form_rating = $('#id_rating');

            $('#rateYo').rateYo({
                fullStar: true,
                rating: form_rating.val() ? form_rating.val() : 0,
                onSet: function (rating, rateYoInstance) {
                    form_rating.val(rating);
                }
            });
        });
    </script>
{% endblock %}

templates/lists/confirm_delete.html
{% extends 'base.html' %}

{% block head_title %}Delete List{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Delete this part list?</h3>
                <hr>
                <form method="post">
                    {% csrf_token %}
                    {% if username %}
                        <span><button formaction="{% url 'profile_del_list' username slug %}" class="btn btn-default">Confirm</button></span>
                    {% else %}
                        <span><button formaction="{% url 'list_del' slug %}" class="btn btn-default">Confirm</button></span>
                    {% endif %}
                    <span><a href="javascript:history.back()" class="btn btn-default">Cancel</a></span>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/lists/list_custom_add_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}{% if item %}Edit {{ item }}{% else %}Add A Custom Item{% endif %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {% crispy form %}
        </div>
    </div>
</div>
{% endblock %}

templates/lists/list_item_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}Edit {{ item }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                {% crispy form %}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}

    <script type="text/javascript">
        $(document).ready(function () {
            var use_custom = {{ use_custom|yesno:"true, false, null" }};

            if (use_custom === true) {
                $('#id_vendor').prop("disabled", true);
                $('#id_choose_price_1').prop("checked", true);
            }
            else if (use_custom === false){
                $('#id_choose_vendor_1').prop("checked", true);
                $('#id_custom_price').prop("disabled", true);
            }

            $('#id_choose_vendor_1').click(function () {
                $('#id_choose_price_1').prop("checked", false);
                $('#id_vendor').prop("disabled", false);
                $('#id_custom_price').prop("disabled", true);
            });

            $('#id_choose_price_1').click(function(){
                $('#id_choose_vendor_1').prop("checked", false);
                $('#id_custom_price').prop("disabled", false);
                $('#id_vendor').prop("disabled", true);
            });
        });
    </script>
{% endblock %}