byog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from common.views import HomePageView, TOSView
from parts import urls as parts_urls
from lists import list_urls, build_urls
from profiles import urls as profile_urls
from articles import urls as article_urls

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^tos/$', TOSView.as_view(), name='tos'),
    url(r'^operator/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^parts/', include(parts_urls)),
    url(r'^lists/', include(list_urls)),
    url(r'^builds/', include(build_urls)),
    url(r'^users/', include(profile_urls)),
    url(r'^article/', include(article_urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lists/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.dispatch import receiver
from django.utils.crypto import get_random_string

from byog.settings import AUTH_USER_MODEL
from common.models import RestrictedImageField, IMAGE_TYPES
from parts.part_info.categories import CATEGORY_CHOICES
from parts.part_info.vendors import VENDOR_CHOICES
from parts.part_info.currency import CURRENCY_CHOICES

import os
import uuid
import decimal

LIST_MAX_PRICE = decimal.Decimal(999999.99)


class ItemList(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.CharField(unique=True, max_length=7)
    active = models.BooleanField(default=True)
    complete = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    title = models.CharField(default='', max_length=100)
    deck = models.CharField(default='', max_length=140)
    description = models.TextField(default='', max_length=5000)
    total_price = models.DecimalField(max_digits=8, decimal_places=2, default=0, blank=True)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='USD')
    date = models.DateTimeField(null=True)

    def save(self, *args, **kwargs):
        """
        Randomly generates a slug on creation
        """
        if not self.slug:
            self.slug = get_random_string(length=7)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        if not self.complete:
            return reverse('list_public', kwargs={'slug': self.slug})
        if self.complete:
            return reverse('build_manage', kwargs={'slug': self.slug})

    def __str__(self):
        return "{} - {}".format(self.user, self.title)


class Build(ItemList):

    class Meta:
        proxy = True


class BuildVote(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    build = models.ForeignKey('ItemList', on_delete=models.CASCADE)

    class Meta:
        unique_together = (
            ('user', 'build')
        )


class Item(models.Model):
    itemlist = models.ForeignKey('ItemList', on_delete=models.CASCADE)
    part = models.ForeignKey('parts.Part', on_delete=models.CASCADE)
    # Since sorted() treats foreignkey values as strings rather than objects, it needs to be set again for the Item
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES, default='', blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    custom_price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    vendor = models.CharField(max_length=15, choices=VENDOR_CHOICES, null=True, blank=True)

    def __str__(self):
        return str(self.part)

    def save(self, *args, **kwargs):
        """
        If the user hasn't selected a vendor, set the vendor with the lowest price
        Automatically set the item category based on the part category
        """
        if not self.vendor:
            self.vendor = self.part.lowest_price_vendor
            self.price = self.part.lowest_price
        if not self.category:
            self.category = self.part.category

        super().save(*args, **kwargs)


class CustomItem(models.Model):
    itemlist = models.ForeignKey('ItemList', on_delete=models.CASCADE)
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES)
    part = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    url = models.URLField(default='', blank=True)

    def __str__(self):
        return "{} - {}".format(self.get_category_display(), self.part)

    @property
    def name(self):
        return self.__str__()


# From http://stackoverflow.com/questions/2673647/enforce-unique-upload-file-names-using-django
def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('img/builds/', filename)


class BuildImage(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    build = models.ForeignKey('ItemList', on_delete=models.CASCADE)
    image = RestrictedImageField(upload_to=get_file_path, content_types=IMAGE_TYPES,
                                 max_upload_size=5242880, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.user:
            self.user = self.build.user
        super().save(*args, **kwargs)


# From http://stackoverflow.com/a/16041527
@receiver(models.signals.post_delete, sender=BuildImage)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes an uploaded image on disk when the associated model is deleted"""

    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=BuildImage)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes file from filesystem when corresponding buildimage object is changed."""

    if not instance.pk:
        return False

    try:
        old_image = BuildImage.objects.get(pk=instance.pk).image

    except BuildImage.DoesNotExist:
        return False

    new_image = instance.image
    if old_image:
        if not old_image == new_image:
            if os.path.isfile(old_image.path):
                os.remove(old_image.path)

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}

{% block head_title %}Build Your Own Gat | BYOG{% endblock %}

{% block content %}
    <div class="container-fluid">
        {% with featured.0 as featured_main %}
            <div class="row">
                <div class="col-md-10 col-md-offset-2">
                    <div class="row">
                        <div class="col-md-8 col-md-push-4">
                            <a href="{{ featured_main.get_absolute_url }}">
                                <div>
                                    {% if featured_main.buildimage_set.all.0 %}
                                        {% thumbnail featured_main.buildimage_set.all.0.image "640x400" crop="center" as im %}
                                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-responsive build-featured-image">
                                        {% endthumbnail %}
                                    {% else %}
                                        <img src="{% static 'img/No_image_available.png' %}" width="400" height="400" class="img-responsive build-featured-image">
                                    {% endif %}
                                </div>
                            </a>
                        </div>
                        <div class="col-md-4 col-md-pull-8 build-featured-main">

                            <h1 class="serif-text"><a href="{% url 'build_featured' %}">Featured Build: </a><br>
                                <a href="{{ featured_main.get_absolute_url }}">{{ featured_main.title }}</a></h1>
                            <p class="build-homepage-featured-user">
                                <a href="{{ featured_main.user.get_absolute_url }}">
                                    <span>
                                        {% if featured_main.user.userprofile.user_image %}
                                            {% thumbnail featured_main.user.userprofile.user_image "36x36" crop="center" as im %}
                                                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                                                     class="img-circle build-featured-profile-image">
                                            {% endthumbnail %}
                                        {% else %}
                                            <img src="{% static 'img/default_avatar.png' %}" width="36" height="36"
                                                 class="img-circle build-featured-profile-image">
                                        {% endif %}
                                    </span>
                                    By {{ featured_main.user }}
                                </a>
                            </p>
                            <p class="serif-text" style="font-size: x-large;">{{ featured_main.deck }}</p>
                            <span><b>{{ featured_main.get_currency_display }}{{ featured_main.total_price }}</b></span>
                            <span class="pull-right"><i class="fa fa-thumbs-o-up fa-fw"
                                                        aria-hidden="true"></i> {{ featured_main.score }}</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10 col-md-offset-1 build-featured-list">
                    <div class="row">
                        {% for build in featured|slice:"1:" %}
                                <div class="col-md-4">
                                    <div>
                                        <a href="{{ build.get_absolute_url }}">
                                            {% if build.buildimage_set.all.0 %}
                                                {% thumbnail build.buildimage_set.all.0.image "380x250" crop="center" as im %}
                                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-responsive build-featured-image">
                                                {% endthumbnail %}
                                            {% else %}
                                                <img src="{% static 'img/No_image_available.png' %}" width="380" height="250" class="img-responsive build-featured-image">
                                            {% endif %}
                                        </a>
                                    </div>
                                    <div style="margin-top: 1.000em;">
                                        <p class="build-homepage-title serif-text"><a href="{{ build.get_absolute_url }}">{{ build.title }}</a></p>
                                        <p>By <a href="{{ build.user.get_absolute_url }}">{{ build.user }}</a></p>
                                    </div>
                                    <div>
                                        <p class="serif-text">{{ build.deck }}</p>
                                        <p>
                                            <span><b>{{ build.get_currency_display }}{{ build.total_price }}</b></span>
                                            <span class="pull-right"><i class="fa fa-thumbs-o-up fa-fw" aria-hidden="true"></i> {{ build.score }}</span>
                                        </p>
                                    </div>
                                </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endwith %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4 build-latest">
                <h4><a href="{% url 'build_list' %}">Latest Builds</a></h4>
                <hr>
                <ul>
                    {% for build in latest %}
                        <li>
                            <div class="row">
                                <div class="col-md-5 build-homepage-img">
                                    <a href="{{ build.get_absolute_url }}">
                                        {% if build.buildimage_set.all.0 %}
                                            {% thumbnail build.buildimage_set.all.0.image "180x100" crop="center" as im %}
                                                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-responsive">
                                            {% endthumbnail %}
                                        {% else %}
                                            <img src="{% static 'img/No_image_available.png' %}" width="54" height="54" class="img-responsive">
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="col-md-6">
                                    <div>
                                        <p class="build-homepage-title serif-text"><a href="{{ build.get_absolute_url }}">{{ build.title }}</a></p>
                                        <p>By <a href="{{ build.user.get_absolute_url }}">{{ build.user }}</a></p>
                                    </div>
                                    <div>
                                        <p class="serif-text">{{ build.deck }}</p>
                                        <p>
                                            <span><b>{{ build.get_currency_display }}{{ build.total_price }}</b></span>
                                            <span class="pull-right"><i class="fa fa-thumbs-o-up fa-fw" aria-hidden="true"></i> {{ build.score }}</span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            {% if not forloop.last %}<hr>{% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="col-md-8 article-homepage">
                <h4><a href="{% url 'article_list' %}">Articles</a></h4>
                <hr>
                <div class="row">
                    {% for article in articles|slice:":2" %}
                        <div class="col-md-6 article-homepage-tile">
                            <a href="{{ article.get_absolute_url }}">
                                <div>
                                    {% thumbnail article.articlecoverimage.image "320x240" crop="center" as im %}
                                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-responsive build-featured-image">
                                    {% endthumbnail %}
                                </div>
                            </a>
                            <div class="build-homepage-byline">
                                <p class="build-homepage-title serif-text"><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></p>
                                <p>By <a href="{{ article.author.get_absolute_url }}">{{ article.author }}</a></p>
                                <p>{{ article.deck }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    {% for article in articles|slice:"2:" %}
                        <div class="col-md-6">
                            <a href="{{ article.get_absolute_url }}">
                                <div>
                                    {% thumbnail article.articlecoverimage.image "320x240" crop="center" as im %}
                                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-responsive build-featured-image">
                                    {% endthumbnail %}
                                </div>
                            </a>
                            <div class="build-homepage-byline">
                                <p class="build-homepage-title serif-text"><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></p>
                                <p>By <a href="{{ article.author.get_absolute_url }}">{{ article.author }}</a></p>
                                <p>{{ article.deck }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/paginator.html
<div class="paginator pull-left">

    <span><small>Page</small></span>

    {% if show_first %}
        <span><a href="?page=1">1</a></span>
        <span>·</span>
    {% endif %}

    {% for one_page in page_numbers %}
        {% if one_page == page %}
            <span class="current-page">{{ page }}</span>
        {% elif one_page != 1 %}
            {% if one_page != pages %}
                <span><a href="?page={{ one_page }}">{{ one_page }}</a></span>
            {% endif %}
        {% endif %}
    {% endfor %}


    {% if show_last %}
        <span>·</span>
        <span><a href="?page=last">{{ pages }}</a></span>
    {% endif %}

</div>

templates/tos.html
{% extends 'base.html' %}

{% block head_title %}Terms of Use and Privacy Policy | BYOG{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>
                    Web Site Terms and Conditions of Use
                </h2>

                <h3>
                    1. Terms
                </h3>

                <p>
                    By accessing this web site, you are agreeing to be bound by these
                    web site Terms and Conditions of Use, all applicable laws and regulations,
                    and agree that you are responsible for compliance with any applicable local
                    laws. If you do not agree with any of these terms, you are prohibited from
                    using or accessing this site. The materials contained in this web site are
                    protected by applicable copyright and trade mark law.
                </p>

                <h3>
                    2. Use License
                </h3>

                <ol type="a">
                    <li>
                        Permission is granted to temporarily download one copy of the materials
                        (information or software) on BYOG's web site for personal,
                        non-commercial transitory viewing only. This is the grant of a license,
                        not a transfer of title, and under this license you may not:

                        <ol type="i">
                            <li>modify or copy the materials;</li>
                            <li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
                            <li>attempt to decompile or reverse engineer any software contained on BYOG's web site;</li>
                            <li>remove any copyright or other proprietary notations from the materials; or</li>
                            <li>transfer the materials to another person or "mirror" the materials on any other server.</li>
                        </ol>
                    </li>
                    <li>
                        This license shall automatically terminate if you violate any of these restrictions and may be terminated by BYOG at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
                    </li>
                </ol>

                <h3>
                    3. Disclaimer
                </h3>

                <ol type="a">
                    <li>
                        The materials on BYOG's web site are provided "as is". BYOG makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, BYOG does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
                    </li>
                </ol>

                <h3>
                    4. Limitations
                </h3>

                <p>
                    In no event shall BYOG or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on BYOG's Internet site, even if BYOG or a BYOG authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
                </p>

                <h3>
                    5. Revisions and Errata
                </h3>

                <p>
                    The materials appearing on BYOG's web site could include technical, typographical, or photographic errors. BYOG does not warrant that any of the materials on its web site are accurate, complete, or current. BYOG may make changes to the materials contained on its web site at any time without notice. BYOG does not, however, make any commitment to update the materials.
                </p>

                <h3>
                    6. Links
                </h3>

                <p>
                    BYOG has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by BYOG of the site. Use of any such linked web site is at the user's own risk.
                </p>

                <h3>
                    7. Site Terms of Use Modifications
                </h3>

                <p>
                    BYOG may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
                </p>

                <h3>
                    8. Governing Law
                </h3>

                <p>
                    Any claim relating to BYOG's web site shall be governed by the laws of the State of California without regard to its conflict of law provisions.
                </p>

                <p>
                    General Terms and Conditions applicable to Use of a Web Site.
                </p>



                <h2>
                    Privacy Policy
                </h2>

                <p>
                    Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
                </p>

                <ul>
                    <li>
                        Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
                    </li>
                    <li>
                        We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.
                    </li>
                    <li>
                        We will only retain personal information as long as necessary for the fulfillment of those purposes.
                    </li>
                    <li>
                        We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned.
                    </li>
                    <li>
                        Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date.
                    </li>
                    <li>
                        We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
                    </li>
                    <li>
                        We will make readily available to customers information about our policies and practices relating to the management of personal information.
                    </li>
                </ul>

                <p>
                    We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained.
                </p>
                </div>
            </div>
    </div>
{% endblock %}