byog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from common.views import HomePageView, TOSView
from parts import urls as parts_urls
from lists import list_urls, build_urls
from profiles import urls as profile_urls
from articles import urls as article_urls

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^tos/$', TOSView.as_view(), name='tos'),
    url(r'^operator/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^parts/', include(parts_urls)),
    url(r'^lists/', include(list_urls)),
    url(r'^builds/', include(build_urls)),
    url(r'^users/', include(profile_urls)),
    url(r'^article/', include(article_urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.conf.urls import url

from profiles import views
from lists import views as list_views

urlpatterns = [
    url(r'^(?P<username>[\w._@+-]{1,30})/$', views.UserProfileView.as_view(), name='profile_user'),
    url(r'^(?P<username>[\w._@+-]{1,30})/create$', views.create_profile, name='profile_create'),
    url(r'^(?P<username>[\w._@+-]{1,30})/edit$', views.edit_profile, name='profile_edit'),
    url(r'^(?P<username>[\w._@+-]{1,30})/lists/$', views.profile_lists, name='profile_lists'),
    url(r'^(?P<username>[\w._@+-]{1,30})/lists/(?P<slug>[A-Za-z0-9]{7})/edit$', list_views.edit_list, name='profile_edit_list'),
    url(r'^(?P<username>[\w._@+-]{1,30})/lists/(?P<slug>[A-Za-z0-9]{7})/del/confirm$', list_views.ListDelConfirmation.as_view(), name='profile_confirm_del_list'),
    url(r'^(?P<username>[\w._@+-]{1,30})/lists/(?P<slug>[A-Za-z0-9]{7})/del$', list_views.del_list, name='profile_del_list'),
    url(r'^(?P<username>[\w._@+-]{1,30})/builds/$', views.profile_builds, name='profile_builds'),
    url(r'^(?P<username>[\w._@+-]{1,30})/builds/(?P<slug>[A-Za-z0-9]{7})/del/confirm$', list_views.ListDelConfirmation.as_view(), name='profile_confirm_del_build'),
    url(r'^(?P<username>[\w._@+-]{1,30})/builds/(?P<slug>[A-Za-z0-9]{7})/del$', list_views.del_list, name='profile_del_build'),
    url(r'^(?P<username>[\w._@+-]{1,30})/settings/$', views.account_settings, name='account_settings'),
]

lists/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.dispatch import receiver
from django.utils.crypto import get_random_string

from byog.settings import AUTH_USER_MODEL
from common.models import RestrictedImageField, IMAGE_TYPES
from parts.part_info.categories import CATEGORY_CHOICES
from parts.part_info.vendors import VENDOR_CHOICES
from parts.part_info.currency import CURRENCY_CHOICES

import os
import uuid
import decimal

LIST_MAX_PRICE = decimal.Decimal(999999.99)


class ItemList(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.CharField(unique=True, max_length=7)
    active = models.BooleanField(default=True)
    complete = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    title = models.CharField(default='', max_length=100)
    deck = models.CharField(default='', max_length=140)
    description = models.TextField(default='', max_length=5000)
    total_price = models.DecimalField(max_digits=8, decimal_places=2, default=0, blank=True)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='USD')
    date = models.DateTimeField(null=True)

    def save(self, *args, **kwargs):
        """
        Randomly generates a slug on creation
        """
        if not self.slug:
            self.slug = get_random_string(length=7)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        if not self.complete:
            return reverse('list_public', kwargs={'slug': self.slug})
        if self.complete:
            return reverse('build_manage', kwargs={'slug': self.slug})

    def __str__(self):
        return "{} - {}".format(self.user, self.title)


class Build(ItemList):

    class Meta:
        proxy = True


class BuildVote(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    build = models.ForeignKey('ItemList', on_delete=models.CASCADE)

    class Meta:
        unique_together = (
            ('user', 'build')
        )


class Item(models.Model):
    itemlist = models.ForeignKey('ItemList', on_delete=models.CASCADE)
    part = models.ForeignKey('parts.Part', on_delete=models.CASCADE)
    # Since sorted() treats foreignkey values as strings rather than objects, it needs to be set again for the Item
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES, default='', blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    custom_price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    vendor = models.CharField(max_length=15, choices=VENDOR_CHOICES, null=True, blank=True)

    def __str__(self):
        return str(self.part)

    def save(self, *args, **kwargs):
        """
        If the user hasn't selected a vendor, set the vendor with the lowest price
        Automatically set the item category based on the part category
        """
        if not self.vendor:
            self.vendor = self.part.lowest_price_vendor
            self.price = self.part.lowest_price
        if not self.category:
            self.category = self.part.category

        super().save(*args, **kwargs)


class CustomItem(models.Model):
    itemlist = models.ForeignKey('ItemList', on_delete=models.CASCADE)
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES)
    part = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    url = models.URLField(default='', blank=True)

    def __str__(self):
        return "{} - {}".format(self.get_category_display(), self.part)

    @property
    def name(self):
        return self.__str__()


# From http://stackoverflow.com/questions/2673647/enforce-unique-upload-file-names-using-django
def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('img/builds/', filename)


class BuildImage(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    build = models.ForeignKey('ItemList', on_delete=models.CASCADE)
    image = RestrictedImageField(upload_to=get_file_path, content_types=IMAGE_TYPES,
                                 max_upload_size=5242880, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.user:
            self.user = self.build.user
        super().save(*args, **kwargs)


# From http://stackoverflow.com/a/16041527
@receiver(models.signals.post_delete, sender=BuildImage)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes an uploaded image on disk when the associated model is deleted"""

    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=BuildImage)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes file from filesystem when corresponding buildimage object is changed."""

    if not instance.pk:
        return False

    try:
        old_image = BuildImage.objects.get(pk=instance.pk).image

    except BuildImage.DoesNotExist:
        return False

    new_image = instance.image
    if old_image:
        if not old_image == new_image:
            if os.path.isfile(old_image.path):
                os.remove(old_image.path)

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.views.generic import DetailView

from profiles.models import UserProfile
from profiles.forms import UserProfileForm
from lists.models import ItemList
from lists.forms import ListDetailForm

from itertools import chain


class UserProfileView(DetailView):
    """
    Displays the user's profile information, if it exists.
    """

    model = UserProfile
    context_object_name = 'profile'
    template_name = 'profiles/profile.html'
    slug_url_kwarg = 'username'
    slug_field = 'user'

    def get_object(self, queryset=None):
        User = get_user_model()
        self.user = get_object_or_404(User.objects.select_related('userprofile'), username=self.kwargs['username'], is_active=True)

        # Sets profile in context if it exists, otherwise the profile page just displays generic information
        # and links to the user's lists and builds.
        try:
            profile = self.user.userprofile
            return profile
        except UserProfile.DoesNotExist:
            pass

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Sets the profile background image and user image in context if they exists,
        # otherwise the defaults are displayed in the rendered template.
        try:
            context['profile_image'] = self.user.userprofile.profile_image
        except UserProfile.DoesNotExist:
            pass

        try:
            context['user_image'] = self.user.userprofile.user_image
        except UserProfile.DoesNotExist:
            pass

        # Explicitly set these in the context instead of from attributes in the template to simplify extending templates
        context['username'] = self.kwargs['username']
        context['date_joined'] = self.user.date_joined
        context['profile_nav'] = 'about'

        return context


@login_required
def create_profile(request, username):
    """
    Creates a user profile.

    Args:
        request: The incoming HttpRequest.  GET request renders the form.  POST request processes form data.
        username: The user the profile is being created for

    Returns:
        form: An instance of UserProfileForm
        Redirects to the main user page.
        403s if a user tries to create another user's profile.
    """

    if request.user.username == username:

        if request.method == 'GET':
            form = UserProfileForm()
            return render(request, 'profiles/profile_create_edit.html', {'form': form})

        elif request.method == 'POST':
            form = UserProfileForm(request.POST, request.FILES)

            if form.is_valid():
                user_image = request.FILES.get('user_image')
                profile_image = request.FILES.get('profile_image')
                form.save(user=request.user, user_image=user_image, profile_image=profile_image)
                return redirect('profile_user', username=username)

    else:
        raise PermissionDenied


@login_required
def edit_profile(request, username):
    """
    Edits an existing user profile.

    Args:
        request: The incoming HttpRequest.  GET request renders the form.  POST request processes form data.
        username: The selected user's username.

    Returns:
        form: An instance of UserProfileForm
        403s if a user tries to edit another user's profile.
    """

    if request.user.username == username:
        profile = UserProfile.objects.get(user__username=username)
        form = None

        if request.method == 'GET':
            form = UserProfileForm(instance=profile)

        elif request.method == 'POST':
            form = UserProfileForm(request.POST, request.FILES)

            if form.is_valid():
                user_image = request.FILES.get('user_image')
                profile_image = request.FILES.get('profile_image')
                # If the user wants to delete their user image/profile image
                clear_user_img = request.POST.get('user_image-clear')
                clear_profile_img = request.POST.get('profile_image-clear')

                form.update(profile=profile, user_image=user_image, clear_user_img=clear_user_img,
                            profile_image=profile_image, clear_profile_img=clear_profile_img)

                return redirect('profile_user', username=username)

        return render(request, 'profiles/profile_create_edit.html', {'form': form})

    else:
        raise PermissionDenied


def profile_lists(request, username):
    """
    Similar to the main list view.
    Displays a list of all the user's list in a sidebar.
    Displays the user's most recent list in the display area by default,
    or whichever list is selected in the GET parameter.

    Args:
        request: The incoming HttpRequest
        username: The selected user's username

    Returns:
        list_set: The set of all the user's created lists
        list_display: The list to be displayed in the display area
        items: items: The combined items and custom items, sorted by category
    """

    User = get_user_model()
    user = get_object_or_404(User.objects.select_related('userprofile'), username=username, is_active=True)
    user_image = None
    profile_image = None

    list_set = ItemList.objects.filter(user=user, complete=False).prefetch_related('item_set__part', 'customitem_set')
    list_active = list_set.filter(active=True).first()
    list_display = None
    combined_items = None

    # Sets the profile background image and user image in context if they exist,
    # otherwise the defaults are displayed in the rendered template.
    try:
        profile = user.userprofile
        profile_image = profile.profile_image
        user_image = profile.user_image

    except UserProfile.DoesNotExist:
        pass

    # TODO Might want to recheck if the prefetch is done at the appropriate spot
    # If there's a view parameter, fetch that specific list
    # Otherwise, display the active list if it exists
    # Otherwise, display the most recent list
    # If the user has no lists, render the template and inform the user as such

    if list_set:

        if request.GET.get('view'):
            list_display = get_object_or_404(list_set, slug=request.GET['view'])
        elif list_active:
            list_display = list_active
        else:
            list_display = list_set.last()

        # Combine and sort items and custom items
        items = list_display.item_set.all()
        custom_items = list_display.customitem_set.all()
        combined_items = sorted(chain(items, custom_items), key=lambda item: (item.category, str(item)))

    return render(request, 'profiles/profile_lists.html', {'list_set': list_set,
                                                           'list_display': list_display,
                                                           'items': combined_items,
                                                           'user_image': user_image,
                                                           'profile_image': profile_image,
                                                           'profile_nav': 'lists',
                                                           'username': username})


def profile_builds(request, username):
    """
    Lists all the user's completed builds

    Args:
        request: The incoming HttpRequest
        username: The selected user's username

    Returns:

    """

    User = get_user_model()
    user = get_object_or_404(User.objects.select_related('userprofile'), username=username, is_active=True)
    user_image = None
    profile_image = None

    build_set = ItemList.objects.filter(user=user, complete=True).prefetch_related('item_set__part', 'customitem_set',
                                                                                   'buildimage_set')
    build_display = None
    combined_items = None

    # Sets the profile background image and user image in context if they exist,
    # otherwise the defaults are displayed in the rendered template.
    try:
        profile = user.userprofile
        profile_image = profile.profile_image
        user_image = profile.user_image

    except UserProfile.DoesNotExist:
        pass

    # Might want to recheck if the prefetch is done at the appropriate spot
    # If there's a view parameter, fetch that specific list
    # Otherwise, display the active list if it exists
    # Otherwise, display the most recent list
    # If the user has no lists, render the template and inform the user as such
    if build_set:

        if request.GET.get('view'):
            build_display = get_object_or_404(build_set, slug=request.GET['view'])
        else:
            build_display = build_set.last()

        items = build_display.item_set.all()
        custom_items = build_display.customitem_set.all()
        combined_items = sorted(chain(items, custom_items), key=lambda item: (item.category, str(item)))

    return render(request, 'profiles/profile_builds.html', {'build_set': build_set,
                                                            'build_display': build_display,
                                                            'items': combined_items,
                                                            'user_image': user_image,
                                                            'profile_image': profile_image,
                                                            'profile_nav': 'builds',
                                                            'username': username})


def account_settings(request, username):
    if request.user.username == username:

        user_image = None
        profile_image = None

        try:

templates/profiles/account_settings.html
{% extends 'profiles/user.html' %}
{% load staticfiles %}
{% load lists_extras %}
{% load thumbnail %}

{% block headtitle %}Account Settings | BYOG{% endblock %}

{% block profile %}
    <div class="row">
        <div class="col-md-12">
            <h3>E-mail Settings</h3>
            <p>Current E-mail: <b>{{ user.email }}</b></p>
            <p><a href="{% url 'account_email' %}">Change E-mail Settings</a></p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <h3>Password Settings</h3>
            <p><a href="{% url 'account_change_password' %}">Change Password</a></p>
        </div>
    </div>
{% endblock %}

templates/profiles/profile.html
{% extends 'profiles/user.html' %}
{% load staticfiles %}
{% load markdown_tags %}

{% block profile %}
    <div>
        <h3>About {{ username }}</h3>
        <hr>
        {% if profile.description %}
            <div class="profile-description serif-text markdown">
                {{ profile.description|mark_down }}
            </div>
        {% elif request.user.username == username %}
            <p>You haven't entered a description yet.</p>
        {% else %}
            <p>{{ username }} hasn't entered a description yet.</p>
        {% endif %}
        <p><small>Date Joined: {{ date_joined }}</small></p>

        {% if request.user.username == username %}
            <hr>
            {% if profile %}
                <a href="{% url 'profile_edit' username %}" class="btn btn-primary"><i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> Edit your profile</a>
            {% else %}
                <a href="{% url 'profile_create' username %}" class="btn btn-primary"><i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> Edit your profile</a>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
           $('.profile-description > table').addClass('table table-bordered table-responsive');
        });
    </script>
{% endblock %}

templates/profiles/profile_builds.html
{% extends 'profiles/user.html' %}
{% load staticfiles %}
{% load lists_extras %}
{% load thumbnail %}

{% block profile %}
    <div class="row">
        {% if build_set %}
            <div class="col-md-3 sidebar">
                    <h4><i class="fa fa-list fa-fw" aria-hidden="true"></i> Completed Builds</h4>
                    <hr>
                    <ul class="list-group">
                        {% for build in build_set %}
                            <li><a href="{% url 'profile_builds' username %}?view={{ build.slug }}" class="list-group-item {% if build.slug == build_display.slug %}a-bold{% endif %}"><i class="fa fa-ellipsis-v fa-fw" aria-hidden="true"></i> {{ build.title }}</a></li>
                        {% endfor %}
                    </ul>
                    {% if user.username == username %}
                        {% if build_display %}
                            <h4 class="serif-text"><i class="fa fa-wrench" aria-hidden="true"></i> Build Management</h4>
                            <hr>
                            <form method="post">
                                {% csrf_token %}
                                <ul class="list-group">
                                    <li><a class="list-group-item" href="{% url 'build_manage' build_display.slug %}"><i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> Edit Build</a></li>
                                    <li><a href="{% url 'profile_confirm_del_build' build_display.user build_display.slug %}" class="list-group-item"><i class="fa fa-trash fa-fw" aria-hidden="true"></i> Delete This Build</a></li>
                                </ul>
                            </form>
                        {% endif %}
                {% endif %}
            </div>

            <div class="col-md-9 profile-build">
                {% if build_display %}
                    <h4><a href="{{ build_display.get_absolute_url }}">{{ build_display.title }}</a></h4>
                        <hr>

                        {% if build_display.buildimage_set.count > 0 %}
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-9">
                                        <div class="img-carousel-profile" id="lightgallery">
                                            {% for img in build_display.buildimage_set.all %}
                                                <div>
                                                    <a href="{{ img.image.url }}" class="lightbox-img">
                                                        {% thumbnail img.image "128x128" crop="center" as im %}
                                                            <img src="{{ im.url }}" height="{{ im.height }}"
                                                                 width="{{ im.width }}"/>
                                                        {% endthumbnail %}
                                                    </a>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}

                        {% if items %}
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th class="text-muted">Category</th>
                                            <th class="text-muted"></th>
                                            <th class="text-muted">Part</th>
                                            <th class="text-muted">Price</th>
                                            <th class="text-muted">Vendor</th>
                                            <th class="text-muted"></th>
                                            <th class="text-muted"></th>
                                        </tr>
                                    </thead>

                                    {% regroup items by get_category_display as category_list %}
                                    <tbody>
                                        {% for category in category_list %}
                                            {% for item in category.list %}
                                                <tr>
                                                    {% if forloop.first %}
                                                        <td width="25%">{{ category.grouper }}</td>
                                                    {% else %}
                                                        <td></td>
                                                    {% endif %}
                                                    <td>
                                                        {% if item.part.image %}
                                                            <a href="{{ item.part.image.url }}">
                                                                {% thumbnail item.part.image "40x40" crop="center" as im %}
                                                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="list-image">
                                                                {% endthumbnail %}
                                                            </a>
                                                        {% else %}
                                                            <img src="{% static 'img/No_image_available.png' %}" class="no-list-image"/>
                                                        {% endif %}
                                                    </td>

                                                    <td>
                                                        {% if item|class_name == 'Item' %}
                                                        <a href="{{ item.part.get_absolute_url }}"><b>{{ item.part }}</b></a>
                                                        {% else %}
                                                        <a href="javascript:void(0);" class="user-url "><b>{{ item.part }}</b></a>
                                                            <br>
                                                            <small class="text-muted"><i>Custom Item</i></small>
                                                        {% endif %}
                                                    </td>

                                                    {% if item|class_name == 'Item' %}
                                                        {% if item.custom_price %}
                                                            <td>${{ item.custom_price }}<br><small class="text-muted"><i>Custom Price</i></small></td>
                                                            <td></td>
                                                        {% elif item.price %}
                                                            <td>${{ item.price }}</td>
                                                            {% if item.vendor %}
                                                                <td><a href="{% url 'parts_vendor' item.part.slug item.vendor %}" >{{ item.get_vendor_display }}</a></td>
                                                            {% else %}
                                                                <td></td>
                                                            {% endif %}
                                                        {% else %}
                                                            <td>N/A</td>
                                                            <td>{{ item.get_vendor_display }}</td>
                                                        {% endif %}
                                                    {% else %}
                                                        <td>${{ item.price }}</td>
                                                        <td></td>
                                                    {% endif %}
                                                </tr>

                                                {% if item|class_name == 'CustomItem' %}
                                                    {% if item.url %}
                                                        <tr class="toggle-url alert alert-warning">
                                                            <td></td>
                                                            <td></td>
                                                            <td colspan="5">
                                                                <div>
                                                                    <b>Warning:</b> This is a user provided URL.  Follow at your own risk.
                                                                </div>
                                                                <div>
                                                                    <b>{{ item.url }}</b>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    {% endif %}
                                                {% endif %}

                                            {% endfor %}
                                        {% endfor %}

                                        <tr>
                                            <td class="td-border-bottom" colspan="7"></td>
                                        </tr>
                                        <tr>
                                            <td colspan="2"></td>
                                            <td align="right"><b>Total:</b></td>
                                            <td><b>{{ build_display.price }}</b></td>
                                        </tr>

                                    </tbody>
                                </table>
                            </div>
                        {% else %}
                            <p>There are no items in this build.</p>
                        {% endif %}

                {% endif %}

        {% else %}
            <h3>{{ username }} hasn't completed any builds yet.</h3>
        {% endif %}

        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            $('.user-url').click(function() {
                $(this).parents('tr').next('.toggle-url').slideToggle('fast');
                return false;
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('.build-description > table').addClass('table table-bordered table-responsive');

            $('.user-url').click(function () {
                $(this).parents('div').next('.build-custom-url').slideToggle('fast');
                return false;
            });

            startSlick('.img-carousel-profile');

            $("#lightgallery").lightGallery({
                selector: '.lightbox-img',
                counter: false
            });
        });

    </script>
{% endblock %}