byog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from common.views import HomePageView, TOSView
from parts import urls as parts_urls
from lists import list_urls, build_urls
from profiles import urls as profile_urls
from articles import urls as article_urls

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^tos/$', TOSView.as_view(), name='tos'),
    url(r'^operator/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^parts/', include(parts_urls)),
    url(r'^lists/', include(list_urls)),
    url(r'^builds/', include(build_urls)),
    url(r'^users/', include(profile_urls)),
    url(r'^article/', include(article_urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parts/urls.py
from django.conf.urls import url

from parts import views

urlpatterns = [
    url(r'^$', views.CategoryAllView.as_view(), name='category_list_all'),
    url(r'^cat/(?P<category>[a-z0-9_]+)/$', views.PartCategoryView.as_view(), name='parts_list_category'),
    url(r'^(?P<slug>[A-Za-z0-9]{7})/(?P<title>[0-9a-z-]+)/$', views.part_detail, name='parts_detail'),
    url(r'^(?P<slug>[A-Za-z0-9]{7})/(?P<title>[0-9a-z-]+)/reviews/$', views.PartReviewList.as_view(),
        name='parts_review_list'),
    url(r'^(?P<slug>[A-Za-z0-9]{7})/(?P<title>[0-9a-z-]+)/reviews/(?P<review_id>[0-9]+)/$', views.part_review_detail,
        name='parts_review_detail'),
    url(r'^(?P<slug>[A-Za-z0-9]{7})/vendor/(?P<vendor>[0-9A-Z]+)/$', views.part_vendor, name='parts_vendor'),
    url(r'^review/(?P<review_id>[0-9]+)/rate$', views.review_vote, name='review_vote'),
    url(r'^dt/(?P<category>[a-z0-9_]+)/$', views.PartsCategoryDT.as_view(), name='parts_dt'),
]

parts/models.py
import os
import uuid
import decimal

from PIL import Image
from django.contrib.postgres.fields import JSONField
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Min, Avg
from django.dispatch import receiver
from django.utils.crypto import get_random_string
from django.utils.text import slugify
from sorl.thumbnail import ImageField

from byog.settings import AUTH_USER_MODEL
from parts.part_info.categories import CATEGORY_CHOICES
from parts.part_info.vendors import VENDOR_CHOICES
from parts.part_info.currency import CURRENCY_CHOICES


# From http://stackoverflow.com/questions/2673647/enforce-unique-upload-file-names-using-django
def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('img/parts/', filename)


class Part(models.Model):
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES, default='')
    manufacturer = models.CharField(max_length=100, default='')
    name = models.CharField(max_length=250, default='')
    product_num = models.CharField(max_length=50, null=True, unique=True, blank=True)
    specs = JSONField(default=dict(), blank=True)
    slug = models.CharField(unique=True, max_length=7)
    lowest_price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    image = ImageField(upload_to=get_file_path, null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_random_string(length=7)

        if not self.lowest_price:
            self.lowest_price = self.pricebase_set.all().aggregate(Min('price'))['price__min']

        if not self.image:
            try:
                self.image = self.partimage_set.first().image
            except AttributeError:
                pass

        if self.product_num == '':
            self.product_num = None

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('parts_detail', kwargs={'slug': self.slug, 'title': slugify(self.__str__())})

    @property
    def lowest_price_vendor(self):
        try:
            price = self.pricebase_set.all().order_by('price').first().vendor
            return price
        except AttributeError:
            return None

    def get_price(self, currency='USD'):
        currency_field = {'USD': self.lowest_price}
        currency_symbol = dict((currency, symbol) for currency, symbol in CURRENCY_CHOICES)

        if currency_field[currency]:
            return "{}{}".format(currency_symbol[currency], currency_field[currency])
        else:
            return None

    @property
    def avg_rating(self):
        reviews = self.partreview_set.filter(build__complete=True)
        if reviews:
            rating = float("{0:.2f}".format(reviews.aggregate(Avg('rating'))['rating__avg']))
        else:
            rating = 0.0

        total = reviews.count()
        average = (rating, total)
        return average


class PriceBase(models.Model):

    part = models.ForeignKey('Part', on_delete=models.CASCADE, default=None)
    vendor = models.CharField(max_length=15, choices=VENDOR_CHOICES)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='USD')
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    date = models.DateField(auto_now_add=True)
    url = models.URLField()

    def __str__(self):
        return self.vendor + ': {}'.format(self.get_currency_display()) + str(self.price)


@receiver(models.signals.post_save, sender=PriceBase)
def auto_update_part_lowest_price(sender, instance, **kwargs):
    """
    Updates a part's lowest_price field if the newly saved base price is lower than the part's current lowest price
    """

    if instance.price:
        if instance.part.lowest_price is None or decimal.Decimal(instance.price) < decimal.Decimal(instance.part.lowest_price):
            instance.part.lowest_price = instance.price
            instance.part.save()


class PricePromo(models.Model):
    base = models.ForeignKey('PriceBase', on_delete=models.CASCADE)
    discount = models.DecimalField(max_digits=6, decimal_places=2)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='USD')
    date_start = models.DateField(auto_now_add=True)
    date_end = models.DateField()
    expired = models.BooleanField(default=False)
    description = models.TextField(max_length=500, default='', blank=True)


class PartReview(models.Model):
    SCORE_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )

    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    part = models.ForeignKey('Part', on_delete=models.CASCADE)
    build = models.ForeignKey('lists.ItemList', on_delete=models.CASCADE)
    item = models.OneToOneField('lists.Item', on_delete=models.CASCADE)
    rating = models.SmallIntegerField(choices=SCORE_CHOICES)
    review = models.TextField(default='', max_length=5000)
    helpful = models.IntegerField(default=0)
    unhelpful = models.IntegerField(default=0)

    def __str__(self):
        return "{} - {}".format(self.part, self.user.username)

    def get_absolute_url(self):
        part = self.part
        return reverse('parts_review_detail', kwargs={'review_id': self.id, 'slug': part.slug, 'title': slugify(part.name)})

    class Meta:
        unique_together = (
            ('part', 'user')
        )

    @property
    def percent_helpful(self):

        if self.helpful + self.unhelpful > 0:

            return "{} of {} user(s) ({:.0%}) found this review helpful.".format(
                self.helpful, (self.helpful + self.unhelpful), (self.helpful / (self.helpful + self.unhelpful))
            )

        else:
            return None


class ReviewVote(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey('PartReview', on_delete=models.CASCADE)
    helpful = models.BooleanField()

    class Meta:
        unique_together = (
            ('review', 'user')
        )


class PartImage(models.Model):
    part = models.ForeignKey('Part', on_delete=models.CASCADE, default=None)
    image = ImageField(upload_to=get_file_path, blank=True)

    def save(self, *args, **kwargs):

        super().save(*args, **kwargs)

        # Resizes the image if it's larger than 500x400
        if self.image:
            filename = self.image
            thumb = Image.open(filename)
            if thumb.height > 400 or thumb.width > 500:
                thumb.thumbnail((500, 400))
                thumb.save(filename.path)


# From http://stackoverflow.com/a/16041527
@receiver(models.signals.post_delete, sender=PartImage)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes an uploaded image on disk when the associated model is deleted"""

    if instance.image:

        if instance.part.image == instance.image:
            instance.part.image = None
            instance.part.save()

        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=PartImage)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes file from filesystem when corresponding partimage object is changed."""

    if not instance.pk:
        return False

    try:
        old_image = PartImage.objects.get(pk=instance.pk).image

    except PartImage.DoesNotExist:
        return False

    new_image = instance.image

    if old_image:

        if not old_image == new_image:

            if instance.part.image == old_image:
                instance.part.image = new_image
                instance.part.save()

            if os.path.isfile(old_image.path):
                os.remove(old_image.path)


@receiver(models.signals.post_save, sender=PartImage)
def auto_add_part_image(sender, instance, **kwargs):
    """Adds an image to a part if one does not already exist"""

    if not instance.part.image:
        instance.part.image = instance.image
        instance.part.save()

parts/forms.py
from django.forms import ModelForm
from parts.models import PartReview

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Field, HTML


class PartReviewForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # crispy forms settings
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Fieldset(
                '{{ part }} review',
                Field('rating', type='hidden'),
                HTML(
                    """
                    <div class='star-rating'>
                        <label>Rating</label>
                        <div id='rateYo'></div>
                        {% if form.errors %}
                            <p class="text-danger"><b>This field is required.</b></p>
                        {% endif %}
                    </div>
                 """
                ),
                'review',
            )
        )
        self.helper.add_input(Submit('submit', 'Save'))

    class Meta:
        model = PartReview
        fields = ['rating', 'review']

    def save(self, user, item, part, build):
        return PartReview.objects.create(user=user, build=build, item=item, part=part,
                                         rating=self.cleaned_data['rating'],
                                         review=self.cleaned_data['review'])

    def update(self, review, item, build):
        review.item = item
        review.build = build
        review.rating = self.cleaned_data['rating']
        review.review = self.cleaned_data['review']
        review.save()

templates/parts/category.html
{% extends 'base.html' %}
{% load parts_extras %}
{% load deslugify %}
{% load parts_extras %}

{% block head_title %}Choose A {{ title }} | BYOG{% endblock %}

{% block content %}
    <div class="container-fluid ">
        <div class="row">
            <div class="col-md-2 sidebar">
                <h4><i class="fa fa-filter fa-fw" aria-hidden="true"></i> Filters</h4>
                <hr>
                <div class="form" id="filter-sidebar">

                    <div class="filter-price" data-spec="price">
                        <small>Price</small>
                        <p>
                            <span id="price-min" class="pull-left" href="#">$0</span> <span id="price-max" class="pull-right" href="#">${{ max_price }}</span>
                            <br>
                            <input id="price-slider" value="" title="Price" data-slider-min="0" data-slider-max="{{ max_price }}" data-slider-value="[0, {{ max_price }}]" data-slider-tooltip="hide" />
                        </p>
                    </div>

                    <div class="filter-list" data-spec="rating">
                        <small>Rating</small>
                        <div class="checkbox">
                            <label><input type="checkbox" value="5">{{ 5|star_ratings }}</label>
                        </div>
                        <div class="checkbox">
                            <label><input type="checkbox" value="4">{{ 4|star_ratings }}</label>
                        </div>
                        <div class="checkbox">
                            <label><input type="checkbox" value="3">{{ 3|star_ratings }}</label>
                        </div>
                        <div class="checkbox">
                            <label><input type="checkbox" value="2">{{ 2|star_ratings }}</label>
                        </div>
                        <div class="checkbox">
                            <label><input type="checkbox" value="1">{{ 1|star_ratings }}</label>
                        </div>
                    </div>

                    <div class="filter-list" data-spec="manufacturer">
                        <small>Manufacturer</small>
                        {% for man in manufacturers %}
                            <div class="checkbox">
                                <label><input type="checkbox" value="{{ man }}">{{ man }}</label>
                            </div>
                        {% endfor %}
                    </div>

                    {% for key, value in specs.items %}
                        <div class="filter-list" data-spec="{{ key }}">
                            <small>{{ key|title|deslugify }}</small>
                            {% for val in value %}
                                <div class="checkbox">
                                    <label><input type="checkbox" value="{{ val }}">{{ val }}</label>
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <hr>
                    <span><button class="btn btn-sm btn-primary" id="filter-button" type="submit"><i class="fa fa-filter fa-fw" aria-hidden="true"></i> Apply Filters</button></span>
                    <span><button class="btn btn-sm btn-danger" id="clear-filters" type="submit"><i class="fa fa-eraser fa-fw" aria-hidden="true"></i> Clear Filters</button></span>
                </div>
            </div>

            <div class="col-md-10 category-table">
                <h4>{% block part_title %}{% endblock %}</h4>
                <hr>
                <div>
                    <table class="table table-striped table-bordered" id="data-table">
                        <thead>
                        <tr>
                            <th>{{ title }}</th>
                            {% for th in thead %}
                                <th>{{ th }}</th>
                            {% endfor %}
                            <th>Rating</th>
                            <th>Price</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            var categoryURL = "{% url 'parts_dt' category %}";
            initDT(categoryURL);
        });

        var priceSlider = $('#price-slider').slider({});
        priceSlider.on("change", function(slideEvt) {
            $("#price-min").text('$' + slideEvt.value.newValue[0]);
            $("#price-max").text('$' + slideEvt.value.newValue[1]);
        });
    </script>
{% endblock %}

templates/parts/category_list_all.html
{% extends 'base.html' %}

{% block head_title %}All Part Categories | BYOG{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% for category in categories %}
                    <h3>{{ category.0 }}</h3>
                    <ul>
                        {% for subcat in category.1 %}

                            <li><a href="{% url 'parts_list_category' subcat.0 %}">{{ subcat.1 }}</a></li>
                        {% endfor %}
                    </ul>
                    {% if not forloop.last %}<hr>{% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/parts/part_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load parts_extras %}
{% load thumbnail %}

{% block head_title %}{{ part }} - {{ part.get_category_display }}| BYOG{% endblock %}

{% block content %}

    <div class="container-fluid part-banner">
        <div class="row">
            <div class="col-md-12">
                <p class="part-category">
                    <b><a href="{% url 'parts_list_category' part.category %}" class=" text-muted ">{{ part.get_category_display|upper }}</a></b>
                </p>
                <h1 class="part-header">{{ part }}</h1>
                <div id="part-star">
                    {{ avg_rating|star_float }}
                </div>
                <p>( {% if avg_rating %}{{ avg_rating }}{% else %}0.0{% endif %} Average / {{ total_reviews }} {% if total_reviews > 1 or total_reviews == 0 %}Ratings{% else %}Rating{% endif %} )</p>
                <form class="part-add-form" role="form" method="post" action="{% url 'item_add' part.id %}">
                    {% csrf_token %}
                    <button class="btn btn-default" type="submit"><i class="fa fa-plus fa-fw" aria-hidden="true"></i> Add To Your List</button>
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            {% if part.partimage_set.count > 0 %}
                <div class="img-carousel" id="lightgallery">
                {% for img in part.partimage_set.all %}
                    <div>
                        <a href="{{ img.image.url }}" class="lightbox-img">
                            {% thumbnail img.image "128x128" crop="center" as im %}
                                <img src="{{ im.url }}" height="{{ im.height }}" width="{{ im.width }}"/>
                            {% endthumbnail %}
                        </a>
                    </div>
                {% endfor %}
            {% else %}
                <div class="jumbotron">
                    <img class="center-block" src="{% static 'img/No_image_available.png' %}"/>
                </div>
            {% endif %}
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-2 sidebar">
                <h4>Specs</h4>
                <hr>
                <p><small>Manufacturer:</small></p>
                <p>{{ part.manufacturer }}</p>
                <hr>
                <p><small>Product #:</small></p>
                <p>{{ part.product_num }}</p>
                <hr>
                {% block spect_table %}
                    {% for key, value in part.specs.items %}
                        <p><small>{{ key|strip_underscore|title }}:</small></p>
                        <p>{{ value }}</p>
                        {% if not forloop.last %}<hr>{% endif %}
                    {% endfor %}
                {% endblock %}
            </div>
            <div class="col-md-10">
                <h4 class="serif-text">Prices</h4>
                <hr>
                <div class="table-responsive">
                    <table class="table table-bordered table-responsive">
                        <thead>
                        <tr>
                            <th>Vendor</th>
                            <th>Base Price</th>
                            <th>Promo</th>
                            <th>Total</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for price in part.pricebase_set.all %}
                            <tr>
                                <td align="center">
                                    <a class="vendor-logo" href="{% url 'parts_vendor' part.slug price.vendor %}">
                                    {% if price.vendor == 'PA' %}
                                        <img src="{% static 'img/logos/primary.jpg' %}"/>
                                    {% elif price.vendor == 'MUSA' %}
                                        <img src="{% static 'img/logos/midway.png' %}"/>
                                    {% elif price.vendor == 'PSA' %}
                                        <img src="{% static 'img/logos/palmetto.png' %}"/>
                                    {% elif price.vendor == 'BRWN' %}
                                        <img src="{% static 'img/logos/brownells.png' %}"/>
                                    {% endif %}
                                    </a>
                                </td>
                                <td>
                                    {% if price.price %}
                                        {{ price.get_currency_display }}{{ price.price }}
                                    {% endif %}
                                </td>
                                <td></td>
                                <td>
                                    {% if price.price %}
                                        <b>{{ price.get_currency_display }}{{ price.price }}</b>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <h4>Price History</h4>
                <hr>
                <img src="{% static 'img/ULnjFuZ.jpg' %}" class="img-responsive"/>
                <h4 class="serif-text">Reviews</h4>
                <hr>
                {% comment %}reviews is a dictionary with usernames for a key and a tuple (review, user profile image) as a value{% endcomment %}
                {% if reviews %}
                    {% for review in reviews %}
                        <div class="row review">
                            <div class="col-md-1">
                                {% if review.user.userprofile.user_image %}
                                    <a href="{{ review.user.get_absolute_url }}">
                                        {% thumbnail review.user.userprofile.user_image "48x48" crop="center" as im %}
                                            <img class="img-circle profile-image-review" src="{{ im.url }}" height="{{ im.height }}" width="{{ im.width }}"/>
                                        {% endthumbnail %}
                                    </a>
                                {% else %}
                                    <a href="{{ review.user.get_absolute_url }}">
                                        <img class="img-circle profile-image-review" src="{% static 'img/default_avatar.png' %}" width="48" height="48">
                                    </a>
                                {% endif %}
                            </div>
                            <div class="col-md-11 review-body">

                                <b><a href="{{ review.user.get_absolute_url }}">{{ review.user.username }}</a></b>
                                {% comment %} This filter converts the int rating into stars {% endcomment %}
                                <div class="review-star"><p>{{ review.rating|star_ratings }} from <a href="{{ review.build.get_absolute_url }}">{{ review.build.title }}</a></p></div>

                                <article>{{ review.review|linebreaks }}</article>
                                <hr class="review-hr">

                                {% if review.percent_helpful %}
                                    <i class="text-muted">{{ review.percent_helpful }}</i>
                                {% endif %}

                                 {% if user.is_authenticated %}
                                    <p class="text-muted"><i>Did you find this review helpful?</i></p>
                                     <div class="review-controls">
                                        <span><a href="javascript:void(0);" onclick="VoteReview({{ review.id }}, true)" class="btn btn-default btn-sm review-button review-helpful"><i class="fa fa-thumbs-up fa-fw" aria-hidden="true"></i> Yes</a></span>
                                        <span><a href="javascript:void(0);" onclick="VoteReview({{ review.id }}, false)" class="btn btn-default btn-sm review-button review-unhelpful"><i class="fa fa-thumbs-down fa-fw" aria-hidden="true"></i> No</a></span>
                                     </div>
                                     <br>
                                {% endif %}
                                <p><a href="{{ review.get_absolute_url }}">Comment</a></p>
                            </div>
                        </div>
                    {% endfor %}
                <h4><a href="{% url 'parts_review_list' part.slug part.name|slugify %}">See all reviews</a></h4>
                {% else %}
                    <p>No reviews found</p>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            startSlick();

            $('.review-helpful').click(function () {
                $(this).removeClass('btn-default').addClass('review-btn-success');
                $(this).parents('.review-controls').find('.review-unhelpful').removeClass('review-btn-danger').addClass('btn-default');
            });

            $('.review-unhelpful').click(function () {
                $(this).removeClass('btn-default').addClass('review-btn-danger');
                $(this).parents('.review-controls').find('.review-helpful').removeClass('review-btn-success').addClass('btn-default');
            });

            $('article').readmore();

            $("#lightgallery").lightGallery({
                selector: '.lightbox-img',
                counter: false
            });
        });
    </script>
{% endblock %}

templates/parts/part_review_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load parts_extras %}

{% block head_title %}{{ review.part }} Review By {{ review.user }} | BYOG{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row review">
                    <div class="col-md-1">
                        {% if review.user.userprofile.user_image %}
                            <a href="{{ review.user.get_absolute_url }}">
                                {% thumbnail review.user.userprofile.user_image "48x48" crop="center" as im %}
                                    <img class="img-circle profile-image-review" src="{{ im.url }}" height="{{ im.height }}" width="{{ im.width }}"/>
                                {% endthumbnail %}
                            </a>
                        {% else %}
                            <a href="{{ review.user.get_absolute_url }}">
                                <img class="img-circle profile-image-review" src="{% static 'img/default_avatar.png' %}" width="48" height="48">
                            </a>
                        {% endif %}
                    </div>
                    <div class="col-md-11 review-body">

                        <b><a href="{{ review.user.get_absolute_url }}">{{ review.user.username }}</a></b>
                        {% comment %} This filter converts the int rating into stars {% endcomment %}
                        <div class="review-star"><p>{{ review.rating|star_ratings }} from <a href="{{ review.build.get_absolute_url }}">{{ review.build.title }}</a></p></div>

                        <article>{{ review.review|linebreaks }}</article>

                        {% if review.percent_helpful %}
                            <hr class="review-hr">
                            <i class="text-muted">{{ review.percent_helpful }}</i>
                        {% endif %}

                         {% if user.is_authenticated %}
                             {% if not review.percent_helpful %}
                                 <hr class="review-hr">
                             {% endif %}
                            <p class="text-muted"><i>Did you find this review helpful?</i></p>
                             <div class="review-controls">
                                <span><a href="javascript:void(0);" onclick="VoteReview({{ review.id }}, true)" class="btn btn-default btn-sm review-button review-helpful"><i class="fa fa-thumbs-up fa-fw" aria-hidden="true"></i> Yes</a></span>
                                <span><a href="javascript:void(0);" onclick="VoteReview({{ review.id }}, false)" class="btn btn-default btn-sm review-button review-unhelpful"><i class="fa fa-thumbs-down fa-fw" aria-hidden="true"></i> No</a></span>
                             </div>
                        {% endif %}
                    </div>
                </div>
                {% if disqus %}
                    {{ disqus|safe }}
                {% endif %}

                <div id="disqus_thread"></div>
                <script>
                    {% if not disqus %}
                        var disqus_config = function () {
                            this.page.url = '{{ site }}';
                            this.page.identifier = '{{ build.slug }}';
                        };
                    {% endif %}

                    (function () { // DON'T EDIT BELOW THIS LINE
                        var d = document, s = d.createElement('script');
                        s.src = '//shiranai-moe.disqus.com/embed.js';
                        s.setAttribute('data-timestamp', +new Date());
                        (d.head || d.body).appendChild(s);
                    })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments
                    powered by Disqus.</a></noscript>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            ReviewVote();
        })
    </script>
{% endblock %}

templates/parts/part_vendor_redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>